#! /bin/sh

blockdate=$(date '+%a. %d. %b. %Y')

case "$BLOCK_BUTTON" in
    1|2|3) date=$(date '+%A, %d. %B')
export TERM=xterm
ncal -h -b \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | tail -n +2 \
    | rofi \
        -dmenu \
        -markup-rows \
        -no-fullscreen \
        -font "Noto Sans 8" \
        -hide-scrollbar \
        -bw 0 \
        -m -3 \
        -theme-str '#window {anchor:southeast; location: northwest;}' \
        -eh 1 \
        -width -30 \
        -no-custom \
	-theme ~/.cache/wal/colors-rofi-dark.rasi \
        -p "$date" > /dev/null 
    esac
echo $blockdate
date '+%d.%m.%Y'
